### ISSUE TITLE
稍微有点延迟，就创建不了了. 帮你改了方法，你要不要加上去?

### ISSUE THREAD

**Issue by dennishappy** [yfGit/YFLinkageScroll#2]
- (void)configItemArr:(NSArray *)itemArr
  {
  self.itemArr = [NSMutableArray arrayWithArray:itemArr];
  
  for (NSUInteger i = 0; i < self.itemArr.count; i++) {
  
  ```
  id item = itemArr[i];
  if ([item isKindOfClass:[UIView class]]) {
  
      self.isView = YES;
      UIView  *itemView = (UIView *)item;
  
      [self addSubview:itemView];
  }else{
      UIViewController  *itemView = (UIViewController *)item;
  
      [self addSubview:itemView.view];
  }
  ```
  
  }
  self.showsHorizontalScrollIndicator = NO;
  self.showsVerticalScrollIndicator   = NO;
  self.pagingEnabled = YES;
  }

**Comment by yfGit** [comment]
谢谢,  已更新.
注意:  是否数据回来后再加载:
 YES -> 代码创建, 数据回来后再初始化.(推荐)
                                                             Xib创建(预加载), 模拟数据, 数据回来后替换, 上面盖一层Loading的画面. 注意标签不要和数据回来的一样, 更换是根据Tag替换对应的内容的..(不推荐) -- 之后有需要加个单更新tag的
NO -> 都可以
